# Generated by Django 4.1.4 on 2023-01-09 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(default=datetime.date(2023, 1, 9)),
        ),
    ]
