# Generated by Django 4.1.4 on 2022-12-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Phones', 'Phones'), ('Laptops', 'Laptops'), ('PC', 'PC')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
