# Generated by Django 4.1.4 on 2023-01-10 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 10)),
        ),
        migrations.AddField(
            model_name='comment',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.goods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to=''),
        ),
    ]
