# Generated by Django 4.1.5 on 2023-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_goods_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('cash', 'cash'), ('visa', 'visa')], max_length=10),
        ),
    ]
